CREATE TABLE IF NOT EXISTS `tasks`(
	id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL,
	short_description TEXT NOT NULL,
	long_description TEXT NOT NULL,
	day DATETIME NOT NULL,
	started DATETIME NULL,
	completed DATETIME NULL,
	PRIMARY KEY(id)
)Engine=InnoDB;

CREATE TABLE IF NOT EXISTS `ideas`(
	id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	title VARCHAR(100) NOT NULL,
	content TEXT NOT NULL,
	added DATETIME NOT NULL,
	PRIMARY KEY(id)
)Engine=InnoDB;